### PR TITLE
Minification of read files for better regex recognition

### PR DESCRIPTION
**Pull request by daverdalas**
Fix issue #33

### CODE REVIEW

**Comment by adriandmitroca** [comment]
@potsky 

Could you please merge this change and tag a new release?

**Comment by daverdalas** [comment]
@potsky
giphy 2

**Comment by potsky** [comment]
Hi !

I will be back in 2 weeks to take a look on your PR. It seems your PR makes all travis CI checks fail...

**Comment by potsky** [comment]
giphy

Available in the next release. Sorry guys for the delay...

**Pull request merged**
